### ISSUE TITLE
Basic how-to?

### ISSUE THREAD

**Issue by jwdinius** [f1tenth/vesc#15]
Is there a walk-through of how to get started with this repo?  I've been able to build a docker image with the catkin workspace built by the steps in your ci job definition, but I'm a little lost as to where to go now.  It would be really helpful to have the following:

1. How to setup the VESC (I think that your link to the vesc project homepage is good, but pointing out the [jetsonhacks website's blog posts](https://www.jetsonhacks.com/2018/02/13/racecar-j-programming-the-electronic-speed-controller/) would be helpful too)
2. Basic build steps (just extract the stages from the ci job and put them in the README)
3. How to connect to a command source; e.g. gamepad or controller

I'm happy to act as the guinea pig and submit a PR with a validated workflow, but I need a little help at this point.  Thanks!

**Comment by JohannesBetz** [comment]
Is this related to the ROS or ROS2 version?
If its about ROS, everything on how to get the car run is explained in detail here: https://f1tenth.readthedocs.io/en/stable/getting_started/driving/index.html# 
Just follow the instructions.

**Comment by jwdinius** [comment]
Thanks @JohannesBetz.  I will check it out.
