### ISSUE TITLE
Error: VescToOdom: Parameter speed_to_erpm_gain is required

### ISSUE THREAD

**Issue by lintglitch** [f1tenth/vesc#2]
When trying to run the vesc to odometry node I am getting the following error:

`$ roslaunch vesc_ackermann vesc_to_odom_node.launch`

`[FATAL] [1610623249.454701135]: VescToOdom: Parameter speed_to_erpm_gain is required.`

I am on a VESC 4.12 board with a 5.1 firmware. Help would be much appreciated.

**Comment by lintglitch** [comment]
Never mind, this was a configuration issue on my end. I'll close this.

**Comment by gtierrezandres** [comment]
@lintglitch what did you change? My launch file currently looks like this: 
![Screenshot from 2021-07-12 15-23-29](https://user-images.githubusercontent.com/48335582/125363336-f5319e00-e35f-11eb-88b5-6046bad65630.png)
but I still get your same error. Any help would be greatly appreciated!

**Comment by jwdinius** [comment]
@gtierrezandres it looks like you are defining the parameters for the wrong node.  You are defining params for `vesc_to_odom_node`, but the params are required for the `ackermann_to_vesc_node`

**Comment by gtierrezandres** [comment]
@jwdinius it is true I noticed that I was using the `vesc_to_odom_node.launch` file instead of this one `ackermann_to_vesc_node.launch`. However, I am still getting the same error

![Screenshot from 2021-07-26 11-38-41](https://user-images.githubusercontent.com/48335582/127041239-091ac19c-478b-42f0-9200-41ca61a7cfc0.png)

Do you have any other suggestions?

**Comment by jwdinius** [comment]
I was able to verify that if I set the parameters from the top-level namespace so that the param is recognized as `speed_to_erpm_gain` and not `/ackermann_to_vesc_node/speed_to_erpm_gain` (and the same for the other 3 required parameters) that the node launched correctly

**Comment by gtierrezandres** [comment]
@jwdinius I'm sorry do you mind specifying where exactly I have to do that?

**Comment by DanielSmetankin** [comment]
> Never mind, this was a configuration issue on my end. I'll close this.

What was the configuration issue on your end?
I am trying to fix the same problem.
The speed_to_erpm_gain is in my vesc.yaml and in my vesc_to_odom_node.launch file. 
I also rebuild everything with catkin_make in my working dir so I don't know what else to do.
I am using ros melodic.
Thanks in advance!

**Comment by DanielSmetankin** [comment]
> @jwdinius I'm sorry do you mind specifying where exactly I have to do that?

I think he is refering to the vesc.yaml but I am not sure.
