### ISSUE TITLE
UART

### ISSUE THREAD

**Issue by TJHBlandon** [f1tenth/vesc#22]
Hi , 

May i ask if the current ros2 branch is able to work if UART is used for communication instead of USB?

Thanks.

**Comment by hzheng40** [comment]
The driver uses [https://index.ros.org/p/serial_driver/#foxy](https://index.ros.org/p/serial_driver/#foxy) for serial communication. Not sure if it works with UART.

**Comment by HaoruXue** [comment]
If you have an UART port on your PC that is listed as one of /dev/tty* then it should work

**Comment by JWhitleyWork** [comment]
The device normally uses UART over USB so it should work just fine. Please re-open this issue if you have any problems.

**Comment by TJHBlandon** [comment]
Alright! Thanks for the response everyone.
