### ISSUE TITLE
Ros2 - Node starts, but no communication to VESC

### ISSUE THREAD

**Issue by Kurtoid** [f1tenth/vesc#5]
I have a VESC 6+ (HW 60). I had it running with ROS kinetic (a while ago), but using the ROS2 node, I can't control it - the node hangs.
The node fails to start if the VESC is unplugged or the port is set incorrectly, as expected. Unplugging the VESC while the node is running stops the node, as expected. I can reach the VESC with the windows config tool. I tested firmware 4.2 and 3.61. It shows up in `lsusb`, and I set the proper udev rule. Any advice?
Edit: testing in Melodic - it works fine there, so it's specific to the ros2 branch

**Comment by JWhitleyWork** [comment]
The ROS2 node is still under development (sorry for the long reply - I didn't see the issue until now). There is no ROS2 serial driver at this point so I am working with a couple of people to get https://github.com/ros-drivers/transport_drivers (the `serial_driver` package) working correctly bi-directionally so we can integrate that into this package. We would love some help, if you're interested.

**Comment by JWhitleyWork** [comment]
@Kurtoid Please test the version at https://github.com/Triton-AI/vesc/tree/ros2 and let me know your results.

**Comment by Kurtoid** [comment]
I'm in the process of moving right now, but I'll check in a couple of days

**Comment by JWhitleyWork** [comment]
No problem. Thanks!

**Comment by JWhitleyWork** [comment]
Closing due to lack of response. If this is still an issue, please open a new ticket.
