### ISSUE TITLE
[Question] VESC 4.12

### ISSUE THREAD

**Issue by edgarcamilocamacho** [f1tenth/vesc#8]
Should it work with VESC 4.12? Or does it only work with VESC 6.0?

**Comment by aravindSolteq** [comment]
Same question.  I use Vesc 4.12 and FW 5.2 ? Does this work for this combination. 
For all other combinations, I get 'Out of Sync error messages"

**Comment by JWhitleyWork** [comment]
Just merged #12 which should help with newer firmware. The hardware version (4.12 vs 6) shouldn't matter but the firmware version does. Please report back after testing!

**Comment by JWhitleyWork** [comment]
Nevermind. Just realized that #12 is just for ROS2 - and the ROS2 version is not yet complete. The version on `main` should be compatible with older revision hardware regardless.
